#!/bin/sh

Hn="$(cat /proc/sys/kernel/hostname)"

#cd /tmp/$Hn/interface-eth0.1
#for file in *; do mv "$file" "${file%-20*}.csv" ;done
#for file in *csv; do mv "$file" "/tmp/runfiles/tmp/LAN_$file" ;done

#cd /tmp/$Hn/interface-eth0.2
#for file in *; do mv "$file" "${file%-20*}.csv" ;done
#for file in *csv; do mv "$file" "/tmp/runfiles/tmp/WAN_$file" ;done


#cd /tmp/$Hn/interface-eth0.3
#for file in *; do mv "$file" "${file%-20*}.csv" ;done
#for file in *csv; do mv "$file" "/tmp/runfiles/tmp/BRWAN_$file" ;done

#cd /tmp/$Hn/cpu-0
#for file in *; do mv "$file" "${file%-20*}.csv" ;done
#for file in *csv; do mv "$file" "/tmp/runfiles/tmp/$file" ;done

#cd /tmp/$Hn/cpu-1
#for file in *; do mv "$file" "${file%-20*}.csv" ;done
#for file in *csv; do mv "$file" "/tmp/runfiles/tmp/$file" ;done

#cd /tmp/$Hn/memory
#for file in *; do mv "$file" "${file%-20*}.csv" ;done
#for file in *csv; do mv "$file" "/tmp/runfiles/tmp/$file" ;done

cd /tmp/$Hn/ping
for file in *; do mv "$file" "${file%.cs*}.csv" ;done
for file in *csv; do mv "$file" "/tmp/runfiles/tmp/$file" ;done

cd /tmp/$Hn/load
for file in *; do mv "$file" "${file%.cs*}.csv" ;done
for file in *csv; do mv "$file" "/tmp/runfiles/tmp/$file" ;done

cd /tmp/$Hn/conntrack
for file in *; do mv "$file" "${file%.cs*}.csv" ;done
for file in *csv; do mv "$file" "/tmp/runfiles/tmp/$file" ;done

#cd /tmp/$Hn/mqtt-Energy
#for file in *; do mv "$file" "${file%-20*}.csv" ;done
#for file in *csv; do mv "$file" "/tmp/runfiles/tmp/$file" ;done

#cd /tmp/$Hn/mqtt-Temp
#for file in *; do mv "$file" "${file%-20*}.csv" ;done
#for file in *csv; do mv "$file" "/tmp/runfiles/tmp/$file" ;done

#cd /tmp/$Hn/mqtt-Flow
#for file in *; do mv "$file" "${file%-20*}.csv" ;done
#for file in *csv; do mv "$file" "/tmp/runfiles/tmp/$file" ;done

#cd /tmp/$Hn/mqtt-Pressure
#for file in *; do mv "$file" "${file%-20*}.csv" ;done
#for file in *csv; do mv "$file" "/tmp/runfiles/tmp/$file" ;done

#cd /tmp/$Hn/mqtt-Humidity
#for file in *; do mv "$file" "${file%-20*}.csv" ;done
#for file in *csv; do mv "$file" "/tmp/runfiles/tmp/$file" ;done

