#!/bin/sh

DS=clearskystatus.info # DataBase Server Address
TS=clearskystatus.info #iperf server address

DT="$(date +%F)"
DTN="iperf-$DT"
Hn="$(cat /proc/sys/kernel/hostname)"
mac="$(cat /sys/class/net/eth0/address | tr ":" "-"   )"
#IP="$(/usr/bin/dig  +short myip.opendns.com @resolver1.opendns.com)"
mkdir /csv/$Hn/iperf
touch /csv/$Hn/iperf/$DTN
if /bin/ping -q -c 2 -W 1 $DS >/dev/null; then
  echo "IPv4 is up"
IP="$(/usr/bin/dig  +short myip.opendns.com @resolver1.opendns.com)"
PING="$(/bin/ping -c 4 $DS |tail -1 | awk '{print $4}' | cut -d '/' -f 2)"

sleep `head /dev/urandom |tr -dc "0123456789" | head -c1 `
sleep `head /dev/urandom |tr -dc "0123456789" | head -c1 `

echo "$mac  $Hn  $IP $TS"
echo "linenew" >> /csv/$Hn/iperf/$DTN
sed -i '1c epoch,Upload,Download,Ping,Pubic_IP,Test_Server' /csv/$Hn/iperf/$DTN #>>/tmp/test.csv
sed -i '/linenew/d' /csv/$Hn/iperf/$DTN

/usr/bin/iperf3 -c $TS | /runfiles/./iperfcsv > /tmp/iperf.tmp
sleep 1
/usr/bin/iperf3 -c $TS -R | /runfiles/./iperfcsvU > /tmp/iperfU.tmp
UL="$(cat  /tmp/iperfU.tmp)"
sed -i "s/.*/&,$UL/" /tmp/iperf.tmp
sed -i "s/.*/&,$PING/" /tmp/iperf.tmp
sed -i "s/.*/&,$IP/" /tmp/iperf.tmp 
sed "s/.*/&,$TS/" /tmp/iperf.tmp >> /csv/$Hn/iperf/$DTN
/usr/bin/rsync -e 'ssh -p 22 -i /root/.ssh/id_rsa' -bvupr -zz /csv/$Hn/iperf/ 'mfnerc\cscremote'@$DS:\csv/$mac/iperf

else
echo "network Down"
fi
