#!/usr/bin/env bash
### speedtest-csv {{SPEEDTEST_CSV_VERSION}}
###
### Usage:
###  speedtest-csv [options]
###
### Options:
###  --header          Display field names (only)
###
###  --header-units    Units (ms, Mbit/s and km) are in header (default)
###  --no-header-units Units are in the values
###  --standardize     Standardize units and number formats (default)
###  --no-standardize  Disable --standardize
###  --share           Generate and provide a URL to the speedtest.net
###                    share results image (default)
###  --no-share        Disable --share
###
###  --quote <str>     Quote fields using <str> (default: none)
###  --sep <str>       Separate fields using <str> (default '\t')
###
###  --help            This help
###  --version         Display version
###
###  --debug           Output extra debug information
###  --last            Use most recent stats, if available
###                    (avoids calling `speedtest-cli`)
###
### Any other options are passed to speedtest-cli as is.
###
### Example:
###  speedtest-csv --header
###  speedtest-csv
###
###  # Defaults in speedtest-csv (<= 1.3.0):
###  speedtest-csv --sep ';' --no-standardize --no-header-units
###
### Installed dependencies:
###  speedtest-cli {{SPEEDTEST_CLI_VERSION}} (https://github.com/sivel/speedtest-cli)
###  python {{PYTHON_VERSION}}
###
### Copyright: 2014-2017 Henrik Bengtsson
### License: GPL (>= 2.1) (https://www.gnu.org/licenses/gpl.html)
call="$0 $*"

SPEEDTEST_CSV_VERSION="2.0.1"

# In case speedtest-cli is in the same directory
# as speedtest-csv, but neither is on the PATH
PATH=$(dirname $0):$PATH

# Temporary file holding speedtest-cli output
user=$USER
if [[ -z $user ]]; then
    user=$USERNAME
fi
log=/tmp/$user/speedtest-csv.log

# Local functions
function mecho() { echo "$@" 1>&2; }
function mdebug() {
    if [[ $debug == true ]]; then
	mecho "[DEBUG] $@";
    fi
}
function str_extract() {
    pattern=$1
    # Extract
    res=`grep "$pattern" $log | sed "s/$pattern//g"`
    # Drop trailing '...'
    res=`echo $res | sed 's/[.][.][.]//g'`
    # WORKAROUND: Drop stray preceeding '.' (Issue #19)
    res=`echo $res | sed 's/^[.]*//g'`
    # Trim
    res=`echo $res | sed 's/^ *//g' | sed 's/ *$//g'`
    echo $res
}

debug=false
header=false
standardize=true
share=true
last=false
version=false
help=false
header_units=true

# Character for separating values
