#!/bin/sh

DS=clearskystatus.info # DataBase Server Address

DT="$(date +%F)"
DTN="speedtest-$DT"
Hn="$(cat /proc/sys/kernel/hostname)"
mac="$(cat /sys/class/net/eth0/address | tr ":" "-"   )"

mkdir /csv/$Hn/speedtest
touch /csv/$Hn/speedtest/$DTN

if /bin/ping -q -c 2 -W 1 $DS >/dev/null; then
  echo "IPv4 is up"

sleep `head /dev/urandom |tr -dc "0123456789" | head -c1 `
sleep `head /dev/urandom |tr -dc "0123456789" | head -c1 `


echo "$mac  $Hn"
echo "linenew" >> /csv/$Hn/speedtest/$DTN 
sed -i '1c epoch, Provider, IP, Test_Server, province, Ping, Download, Upload' /csv/$Hn/speedtest/$DTN #>>/tmp/test.csv
sed -i '/linenew/d' /csv/$Hn/speedtest/$DTN

/runfiles/./speedtest-csv-epoch >>/csv/$Hn/speedtest/$DTN
/usr/bin/rsync -e 'ssh -p 22 -i /root/.ssh/id_rsa' -bvupr -zz /csv/$Hn/speedtest/ 'mfnerc\cscremote'@$DS:\csv/$mac/speedtest
sleep 6660
/runfiles/./iperfrsync
else
echo "network Down"
fi
